config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  
    resources :users do
      resources :posts
  end
  
  resources :mypages, only:[:index,:show]
  
  root "messages#index"
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy #postが削除されたら一緒に削除
  validates :name, :image, :text, presence: true
  mount_uploader :image, ImageUploader

  def like_user(user_id)
    likes.find_by(user_id: user_id)#そのユーザーが持っているlikeを探す
  end

  def self.search(search)
    if search
      Post.where('text LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: true
  has_many :posts
  has_many :likes, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  

  protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = Like.new(user_id: @current_user.id, post_id: params[:post_id])#投稿ユーザーと内容
    @likes = Like.where(post_id: params[:post_id])#いいねの合計数 #使われてないので必要ない？
    @like.save
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])#いいねの合計数
    @post.reload
  end

  private
  
  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def index
    @posts = Post.where(user_id: current_user.id ).page(params[:page]).per(5).order("created_at DESC")
  end


  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update,:destroy]

  def index
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(5)
    @posts = @posts.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
    logger.debug("JS_test")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to root_path
  end

  def show
    
  end  

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post.id)
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end
  


private
  def set_post
    @post = Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(:name, :image, :text, :user_id).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FiveMinutesRecipe
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield 

app/views/likes/_like.html.haml
-unless post.like_user(current_user.id).blank? 
  = link_to post_like_path(post_id: post.id, id: post.likes[0].id), method: :delete, remote: true do
    .vertical_like
      = link_to "#", class: "star-btn" do
        = icon('fas', 'star')
      %span.star-btn
        = post.likes_count
- if post.likes_count > 0
  .vertical_like
    = link_to "#", class: "star-btn" do
      = icon('fas', 'star')
    %span.star-btn
      = post.likes_count
- else
  .vertical_like
    = link_to "#", class: "star-btn" do
      = icon('fas', 'star')
    %span.white-star-btn
      = post.likes_count
      

app/views/likes/create.js.haml
# :javascript
#   console.log('js_create');
  
# :javascript
# $('#likes_buttons_ #{@post.id}').html("#{j(render partial: 'likes/like', locals: {post: @post})}");

# :javascript
#   console.log('js');

app/views/likes/destroy.js.haml
# :javascript
#   console.log('js_root');
  
# :javascript
# $('#likes_buttons_ #{@post.id}').html("#{j(render partial: 'likes/like', locals: {post: @post})}");

app/views/mypages/index.html.haml
.header
  .header__logo
    = link_to root_path do
      %h1 My Page
          
      .header__logo__search-box
        = link_to edit_user_path(current_user) do
          edit
          = icon('fas', 'cog', class: 'icon')
      .header__logo__login-box
        = link_to destroy_user_session_path, method: :delete, class: "login__btn" do
          logout
          = icon('fas', 'sign-out-alt')

.user-galleries
  %h3.user-name
    = current_user.name
  .wrapper
  - @posts.each do |post|
    .user-gallery.clearfix
      .user-gallery__right
        = link_to post_path(post.id) do
          = image_tag post.image.to_s
        = post.name
      -# .user-gallery__left
      -#   = link_to post_path(post.id) do
      -#     = image_tag post.image.to_s
      -#   %p レシピ名
      -#   = post.name
  = paginate(@posts)     

.footer
  .item-button
    = link_to "#", class: "memo-btn" do
      = icon('far', 'file-alt')
    = link_to root_path, class: "index-btn" do
      = icon('fas', 'utensils')
    = link_to new_post_path class: "camera-btn" do
      = icon('fas', 'camera')
    = link_to "#", class: "star-btn" do
      = icon('fas', 'star')
    = link_to mypages_path, class: "mypage-btn" do
      = icon('fas', 'user')

app/views/mypages/show.html.haml
.header
  .header__logo
    = link_to root_path do
      %h1 User Page
          
      .header__logo__search-box
        = link_to edit_user_path(current_user) do
          edit
          = icon('fas', 'cog', class: 'icon')
      .header__logo__login-box
        = link_to destroy_user_session_path, method: :delete, class: "login__btn" do
          logout
          = icon('fas', 'sign-out-alt')

.user-galleries
  %h3.user-name
    = @user.name
  .wrapper
  - @posts.each do |post|
    .user-gallery.clearfix
      .user-gallery__right
        = link_to post_path(post.id) do
          = image_tag post.image.to_s
        = post.name
  -# = paginate(@posts)     

.footer
  .item-button
    = link_to "#", class: "memo-btn" do
      = icon('far', 'file-alt')
    = link_to root_path, class: "index-btn" do
      = icon('fas', 'utensils')
    = link_to new_post_path class: "camera-btn" do
      = icon('fas', 'camera')
    = link_to "#", class: "star-btn" do
      = icon('fas', 'star')
    = link_to mypages_path, class: "mypage-btn" do
      = icon('fas', 'user')

app/views/posts/_footer.html.haml
.footer
  .item-button
    -if user_signed_in?
      = link_to "#", class: "memo-btn" do
        = icon('far', 'file-alt')
      = link_to root_path, class: "index-btn" do
        = icon('fas', 'utensils')
      = link_to new_post_path class: "camera-btn" do
        = icon('fas', 'camera')
      = link_to "#", class: "star-btn" do
        = icon('fas', 'star')
      = link_to mypages_path, class: "mypage-btn" do
        = icon('fas', 'user')
    
  

app/views/posts/_header.html.haml
.header
  .header__logo
    = link_to root_path do
      %h1 5MR
    %p.title 簡単5分クッキング
      

    -if user_signed_in?
      .header__logo__login-box
        = form_with url: posts_path, method: :get, local: true do |form|
          = form.text_field :search
          = form.submit 'Search', name: nil

    -else
      .header__logo__signup-box
        = link_to new_user_registration_path class: "signup__btn" do
          sign up
          = icon('fas', 'user-plus')
      .header__logo__user-box
        = link_to new_user_session_path class: "login__btn" do
          log in
          = icon('fas', 'sign-in-alt')   

app/views/posts/edit.html.haml
= render "header"
.new-contents
  = form_with model: @post, local: true do |form|
    .form-contents
      %h3 編集する
      = form.text_field :name,  placeholder: "Title", size: "50", class: "form-title"
      = form.text_area :text,  placeholder: "Recipe", cols: "50", rows:"10", class: "form-recipe"
      = form.label :image, class: "form-image" do
        = icon('fa', 'image')
        = form.file_field :image, class: "form-control"
      = form.submit "SEND", class: "form-send"
= render "footer"

app/views/posts/index.html.haml
= render "header"  
.galleries
  %h2.recipe みんなのレシピ
  .wrapper
  - @posts.each do |post|
    %ul.index-gallery
      %li.index-gallery__photo
        = link_to post_path(post.id) do
          = image_tag post.image.to_s
      -if user_signed_in?    
        %li.index-gallery__user--name
          = link_to mypage_path(post.user) do
            = post.user.name
        %div{id: "likes_buttons_ #{post.id}"}
        = render partial: 'likes/like', locals: { post: post, likes: @likes}
      -else 
        %li.index-gallery__user--name
          = post.user.name
          
  = paginate(@posts)
= render "footer"

app/views/posts/new.html.haml
= render "header"
.new-contents
  = form_with model: @post, local: true do |form|
    .form-contents
      %h3 投稿する
      = form.text_field :name,  placeholder: "Title", size: "50", class: "form-title"
      = form.text_area :text,  placeholder: "Recipe", cols: "50", rows:"10", class: "form-recipe"
      = form.label :image, class: "form-image" do
        = icon('fa', 'image')
        = form.file_field :image, class: "form-control"
      = form.submit "SEND", class: "form-send"
= render "footer"

app/views/posts/show.html.haml
.header
  .header__logo
    = link_to root_path do
      %h1 5MR
      %p.title レシピ
      -# .header__logo__search-box
      -#   = link_to "#", class: "search__btn" do
      -#     search
      -#     = icon('fas', 'search')
.show-content
  .post-title
    = @post.name
  .post-date
    = @post.created_at.strftime("%Y-%m-%d")
  .post-image
    = image_tag @post.image.url
  .post-recipe
    = simple_format(@post.text)
    
  - if user_signed_in? && current_user.id == @post.user_id
    = link_to  edit_post_path(@post.id), class: "edit-button" do
      edit
    = link_to  post_path(@post.id), method: :delete, class: "delete-button" do
      delete
= render "footer"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'